"""Opt-in, content-free metrics for local server usage."""

from __future__ import annotations

import os
import threading
import time
from collections import defaultdict
from contextlib import contextmanager
from typing import Any, Iterator


EVENT_NAMES = (
    "captures",
    "searches",
    "empty_searches",
    "capture_to_search",
    "retrievals",
    "search_to_retrieval",
    "evictions",
    "cleanups",
)

BYTE_COUNTER_NAMES = (
    "capture_input_bytes",
    "capture_retained_bytes",
    "capture_original_bytes",
    "tool_response_bytes",
    "search_response_bytes",
    "retrieval_response_bytes",
    "socket_request_bytes",
    "socket_response_bytes",
)

MCP_TOOL_NAMES = (
    "preflight_command",
    "start_execution",
    "resume_execution",
    "get_execution",
    "get_execution_output",
    "list_executions",
    "capture_text",
    "capture_file",
    "execute_and_capture",
    "consolidate_captures",
    "search_capture",
    "get_capture_slice",
    "get_capture_summary",
    "list_captures",
    "clear_captures",
    "get_buffer_stats",
    "get_runtime_diagnostics",
    "set_semantic_index_budget",
)


def metrics_enabled() -> bool:
    """Return whether local metrics were explicitly enabled."""
    return os.environ.get("EPHEMERAL_METRICS", "").strip().lower() in {
        "1", "true", "yes", "on"
    }


class LocalMetrics:
    """Bounded in-process counters and timers with no content storage."""

    def __init__(self, enabled: bool | None = None):
        self.enabled = metrics_enabled() if enabled is None else enabled
        self._lock = threading.Lock()
        self._tools: dict[str, dict[str, Any]] = defaultdict(self._new_tool)
        self._events: dict[str, int] = defaultdict(int)
        self._bytes: dict[str, int] = defaultdict(int)
        self._captured: set[str] = set()
        self._searched: set[str] = set()

    @staticmethod
    def _new_tool() -> dict[str, Any]:
        return {
            "calls": 0,
            "successes": 0,
            "failures": 0,
            "total_duration_ms": 0.0,
            "max_duration_ms": 0.0,
            "result_count": 0,
        }

    @contextmanager
    def measure(self, tool: str) -> Iterator[dict[str, Any]]:
        """Measure one tool call; the yielded state may contain result_count.

        Count the call at entry so snapshots generated by a diagnostic tool
        include that in-flight tool in interface coverage.
        """
        state = {"success": True, "result_count": None}
        started = time.perf_counter()
        if self.enabled:
            with self._lock:
                self._tools[tool]["calls"] += 1
        try:
            yield state
        except Exception:
            state["success"] = False
            raise
        finally:
            if self.enabled:
                duration_ms = (time.perf_counter() - started) * 1000
                with self._lock:
                    stats = self._tools[tool]
                    stats["successes" if state["success"] else "failures"] += 1
                    stats["total_duration_ms"] += duration_ms
                    stats["max_duration_ms"] = max(stats["max_duration_ms"], duration_ms)
                    if state["result_count"] is not None:
                        stats["result_count"] += int(state["result_count"])

    def record_event(self, event: str) -> None:
        if self.enabled:
            with self._lock:
                self._events[event] += 1

    def record_bytes(self, counter: str, amount: int) -> None:
        """Record a non-content byte count for the current server session."""
        if self.enabled:
            if counter not in BYTE_COUNTER_NAMES:
                raise ValueError(f"unknown byte counter: {counter}")
            with self._lock:
                self._bytes[counter] += max(0, int(amount))

    def record_result_count(self, tool: str, count: int) -> None:
        if self.enabled:
            with self._lock:
                self._tools[tool]["result_count"] += max(0, int(count))

    def record_capture(self, capture_id: str) -> None:
        if self.enabled:
            with self._lock:
                self._captured.add(capture_id)
                self._events["captures"] += 1

    def record_search(self, capture_id: str, match_count: int) -> None:
        if self.enabled:
            with self._lock:
                if capture_id in self._captured:
                    self._events["capture_to_search"] += 1
                    self._searched.add(capture_id)
                self._events["searches"] += 1
                self._events["empty_searches"] += int(match_count == 0)

    def record_retrieval(self, capture_id: str) -> None:
        if self.enabled:
            with self._lock:
                if capture_id in self._searched:
                    self._events["search_to_retrieval"] += 1
                self._events["retrievals"] += 1

    def forget_capture(self, capture_id: str) -> None:
        if self.enabled:
            with self._lock:
                self._captured.discard(capture_id)
                self._searched.discard(capture_id)

    def snapshot(self) -> dict[str, Any]:
        """Return aggregate metrics suitable for a content-free diagnostic."""
        if not self.enabled:
            return {"enabled": False}
        with self._lock:
            used_tools = [name for name in MCP_TOOL_NAMES if name in self._tools]
            unused_tools = [name for name in MCP_TOOL_NAMES if name not in self._tools]
            available_tools = len(MCP_TOOL_NAMES)
            return {
                "enabled": True,
                "interface_coverage": {
                    "used": len(used_tools),
                    "available": available_tools,
                    "percentage": round(len(used_tools) / available_tools * 100, 1)
                    if available_tools
                    else 0.0,
                    "unused_tools": unused_tools,
                },
                "tools": {
                    name: {
                        **stats,
                        "total_duration_ms": round(stats["total_duration_ms"], 3),
                        "max_duration_ms": round(stats["max_duration_ms"], 3),
                    }
                    for name, stats in self._tools.items()
                },
                "events": {name: self._events[name] for name in EVENT_NAMES},
                "bytes": {name: self._bytes[name] for name in BYTE_COUNTER_NAMES},
            }
